### ISSUE TITLE
Wieso kann ich da nichts ändern du kek

### ISSUE THREAD

**Issue by Nikasukee** [LeXonJe/moron#1]
<html>

  <head>
  </head>
  
  <body>
    <h1> Gib ma Admin du kek </h1>
  </body>
  
</html>

**Comment by LeXonJe** [comment]
Sehr geehrter Herr Nikasukee,

ich muss Sie bedauerlicherweise darüber informieren, dass dies eine persönliche Repo ist und ich Ihnen deswegen kein Admin geben kann. Wenn Sie etwas zum Projekt beitragen wollen, dann können Sie das gerne über eine Pull Request machen.

MfG
LeXonJe

**Comment by Nikasukee** [comment]
Oh, das erschüttert mich zutiefst. Hoffentlich haben sie später eine
Möglichkeit mich zu diesem Privaten Repo hinzuzufügen.

LeXonJe ***@***.***> schrieb am Do. 13. Jan. 2022 um 16:15:

**Comment by LeXonJe** [comment]
Nein.
